apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app:68
spec:
  selector:
    matchLabels:
      app: flask-app:68
  template:
    metadata:
      labels:
        app: flask-app:68
    spec:
      containers:
      - name: flask-app:68
        image: kashifsadiq/flask-app:68
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
